apiVersion: v1
kind: Service
metadata:
  name: survey-client-service
  labels:
    app: web
    role: web-client
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web
    role: web-client
    tier: frontend