apiVersion: v1
kind: ReplicationController
metadata:
  name: survey-client-contro
  labels:
    app: web
    role: web-client
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        role: web-client
        tier: frontend
    spec:
      containers:
      - name: survey-client
        image: djob195/survey-client
        resources:
          requests:
            cpu: 100m
            memory: 100Mi                                                                                          
        ports:
        - containerPort: 80